name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Build
        run: |
          mkdir -p dist/${{ matrix.goos }}-${{ matrix.goarch }}
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/${{ matrix.goos }}-${{ matrix.goarch }}/GitRelease

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        if: success()
        with:
          files: dist/${{ matrix.goos }}-${{ matrix.goarch }}/GitRelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}